topics_mapping = {
    'Programming language': 'Programming language',
    'Artificial intelligence': 'Artificial intelligence',
    'Operating system': 'Operating system',
    'Telecommunications': 'Telecommunications',
    'Algorithm': 'Algorithm',
    'Computer network': 'Computer network',
    'World Wide Web': 'World Wide Web',
    'Machine learning': 'Artificial intelligence',
    'Computer vision': 'Artificial intelligence',
    'Library science': 'Scientometrics',
    'Computer security': 'Computer security',
    'Linguistics': 'Linguistics',
    'Citation': 'Scientometrics',
    'Set (abstract data type)': 'Programming language',
    'Space (punctuation)': 'Programming language',
    'Process (computing)': 'Operating system',
    'Crystal (programming language)': 'Programming language',
    'Computer network': 'Telecommunications',
    'Channel (broadcasting)': 'Telecommunications',
    'Data science': 'Data science',
    'Data mining': 'Data science',
    'Information retrieval': 'Data science',
}

application_domains_mapping = {
    'Physics': 'Physics',
    'Quantum mechanics': 'Physics',
    'Optics': 'Physics',
    'Mathematics': 'Mathematics',
    'Biology': 'Biology',
    'Chemistry': 'Chemistry',
    'Medicine': 'Medicine',
    'Engineering': 'Engineering',
    'Environmental science': 'Environmental science',
    'Materials science': 'Materials science',
    'Mathematical analysis': 'Mathematics',
    'Geometry': 'Mathematics',
    'Philosophy': 'Philosophy',
    'Statistics': 'Statistics',
    'Organic chemistry': 'Chemistry',
    'Economics': 'Economics',
    'Business': 'Economics',
    'Electrical engineering': 'Engineering',
    'Electronic engineering': 'Engineering',
    'Psychology': 'Psychology',
    'Political science': 'Political science',
    'Law': 'Law',
    'Geography': 'Geography',
    'Internal medicine': 'Medicine',
    'Geology': 'Geology',
    'Pure mathematics': 'Mathematics',
    'Biochemistry': 'Chemistry',
    'Sociology': 'Sociology',
    'Thermodynamics': 'Physics',
    'Crystallography': 'Physics',
    'Control (management)': 'Management',
    'Epistemology': 'Philosophy',
    'Composite material': 'Materials science',
    'Mechanical engineering': 'Engineering',
    'Ecology': 'Environmental science',
    'Gene': 'Biology',
    'Pathology': 'Medicine',
    'Voltage': 'Physics',
    'Paleontology': 'Paleontology',
    'Genetics': 'Biology',
    'Archaeology': 'Archaeology',
    'Molecule': 'Chemistry',
    'Astronomy': 'Astronomy',
    'Applied mathematics': 'Mathematics',
    'Nuclear physics': 'Physics',
    'Image (mathematics)': 'Mathematics',
    'Optoelectronics': 'Engineering',
    'Acoustics': 'Physics',
    'Statistical physics': 'Physics',
    'Combinatorics': 'Mathematics',
    'Finance': 'Economics',
    'Control theory (sociology)': 'Sociology',
    'Power (physics)': 'Physics',
    'Crystal structure': 'Physics',
    'Diffraction': 'Physics',
    'Context (archaeology)': 'Archaeology',
    'Art': 'Art',
    'Group (periodic table)': 'Chemistry',
    'Neuroscience': 'Medicine',
    'Condensed matter physics': 'Physics',
    'Atomic physics': 'Physics',
    'Disease': 'Medicine',
    'Mathematical optimization': 'Mathematics',
}