topics_mapping = {
    'Programming language': 'Programming language',
    'Artificial intelligence': 'Artificial intelligence',
    'Operating system': 'Operating system',
    'Telecommunications': 'Telecommunications',
    'Algorithm': 'Algorithm',
    'Computer network': 'Computer network',
    'World Wide Web': 'World Wide Web',
    'Machine learning': 'Artificial intelligence',
    'Computer vision': 'Artificial intelligence',
    'Library science': 'Scientometrics',
    'Computer security': 'Computer security',
    'Linguistics': 'Linguistics',
    'Citation': 'Scientometrics',
    'Set (abstract data type)': 'Programming language',
    'Space (punctuation)': 'Programming language',
    'Process (computing)': 'Operating system',
    'Crystal (programming language)': 'Programming language',
    'Computer network': 'Telecommunications',
    'Channel (broadcasting)': 'Telecommunications',
    'Data science': 'Data science',
    'Data mining': 'Data science',
    'Information retrieval': 'Data science',
}

application_domains_to_delete = [
    "internet",
    "The Internet",
    "Fuzzy logic",
    "Convolutional neural network",
    "neural network",
    "Logic programming",
    "Iterative method",
    "Artificial neural network",
    "Cloud computing",
    "Exploit",
    "Deep learning",
    "Expert system",
    "Humancomputer interaction",
    "File management",
    "Synchronizing",
    "Parsing",
    "database",
    "computer",
    "Operational semantics",
    "Simplicity",
    "Theoretical computer science",
    "Computer science",
    "Computer hardware",
    "Analog computer",
    "Download",
    "Software",
    "Algorithms",
    "Computation",
    "Icon",
    "Subject (documents)",
    "Natural language processing",
    "Human computer interaction",
    "Software engineering",
    "Database",
    "Parallel computing",
    "Distributed computing",
    "Semantics (computer science)",
    "Computer graphics (images)",
    "Binary number",
    "Human-computer interaction",
    "Noise (video)",
    "Speech recognition",
    "State (computer science)",
    "Logic gate",
    "Mercury (programming language)",
    "Computer engineering",
    "League",
    "Internet privacy",
    "Computational linguistics",
    "Fortran",
    "Wish",
    "Decoding methods",
    "Asynchronous communication",
    "Table (database)",
    "Block diagram",
    "FLOPS",
    "Modular design",
    "NAND logic", 
    "NAND gate", 
    "Integer programming",
    "Integer (computer science)",
    "Network analysis",
    "Data acquisition",
    "Stability (learning theory)",
    "Jitter",
    "Microprocessor",
    "Computer-aided",
    "Automaton",
    "Computational science",
    "Decomposition",
    "Microcode",
    "Pseudorandom number generator",
    "Comparison of multi-paradigm programming languages",
    "Object (grammar)",
    "Computer architecture",
    "Disk formatting",
    "Finite-state machine",
    "Wright",
    "Bandwidth (computing)",
    "Citation database",
    "Thin film",
    "Diagram",
    "Von Neumann architecture",
    "Hypertext",
    "Sampling (signal processing)",
    "Cellular automaton",
    "SIGNAL (programming language)",
    "Conjugate gradient method",
    "IBM",
    "Minification",
    "Memorization",
    "Dynamic programming",
    "IBM PC compatible",
    "Human-",
    "LTI system theory",
    "programming",
    "Relational database",
    "Logic programming",
    "Observability",
    "Controllability",
    "Operand",
    "Principal (computer security)",
    "Experimental data",
    "Minicomputer",
    "Foundation (evidence)",
    "Documentation",
    "Natural language",
    "Image processing",
    "Abstraction",
    "Fault tolerance",
    "Key (lock)",
    "Interpolation (computer graphics)",
    "Parallelism (grammar)",
    "Software portability",
    "Interpolation (computer graphics)",
    "Interpreter",
    "Proof assistant",
    "Microcomputer",
    "Path (computing)",
    "Architecture",
    "Petri net",
    "Scalability",
    "Inter frame",
    "Abstract data type",
    "Computing",
    "Grammar",
    "Genetic algorithm",
    "Computer programming",
    "Evidence",
    "Exchange"
]

application_domains_mapping = {
    "Topology" : "Mathematics",
    "Semiconductor" : "Engineering",
    "Alternating current" : "Engineering",
    "Chemical analysis" : "Chemistry",
    "Predicate logic" : "Mathematics",
    "Signal processing" : "Engineering",
    "Commutative property" : "Mathematics",
    "Property (philosophy)" : "philosophy",
    "Dynamical systems theory" : "Mathematics",
    "Section (typography)" : "Linguistics",
    "Readability" : "Linguistics",
    "Signal-to-noise ratio (imaging)" : "Engineering",
    "Gear tooth" : "Engineering",
    "Deflection (physics)" : 'Physics',
    "Wireless" : "Engineering",
    "Interference (communication)" : "Engineering",
    "Data transmission" : "Engineering",
    "Optical communication" : "Engineering",
    "Task (project management)" : "Economics",
    "Office automation" : "Economics",
    "Automation" : "Economics",
    "Parametric statistics" : "Mathematics",
    "Code (set theory)" : "Mathematics",
    "Mathematical proof" : "Mathematics",
    "Variable (mathematics)" : "Mathematics", 
    "Basis (linear algebra)" : "Mathematics",
    "Center (category theory)" : "Mathematics",
    "Presentation (obstetrics)" : "Medicine",
    "Obstetrics" : "Medicine",
    "Neutron" : 'Physics',
    "Electromagnetic field" : 'Physics',
    "Medical physics" : "Medicine",
    "Remote sensing" : "Engineering",
    "Control engineering" : "Engineering",
    "Pattern recognition (psychology)" : "Medicine",
    "Interface (matter)" : 'Physics',
    "Plan (archaeology)" : "Archaeology",
    "Limit (mathematics)" : "Mathematics", 
    "Coding (social sciences)" : "Social sciences",
    "Architectural engineering" : "Engineering",
    "Limit (mathematics)" :  "Mathematics", 
    "Matching (statistics)" :  "Mathematics",
    "Algebraic number" :  "Mathematics", 
    "Management" : "Economics",
    "LTI system theory" : "Mathematics", 
    "Linear system" : "Mathematics",
    "Coding (social sciences)" : "Social sciences",
    "Architectural engineering" : "Engineering",
    "Order (exchange)" : "Economics",
    "Position (finance)" : "Economics",
    "Quadratic equation" : "Mathematics",
    "Bounded function" : "Mathematics",
    "Demodulation" : "Engineering",
    "Transmission (telecommunications)" : "Engineering",
    "Structural engineering" : "Engineering",
    "Phase (matter)" : 'Physics',
    "Extension (predicate logic)" : "Mathematics", 
    "Zero (linguistics)" : "Linguistics",
    'Physics': 'Physics',
    'Quantum mechanics': 'Physics',
    'Optics': 'Physics',
    'Mathematics': 'Mathematics',
    'Biology': 'Biology',
    "Operator (biology)" : 'Biology', 
    "Type (biology)" : 'Biology', 
    'Chemistry': 'Chemistry',
    'Medicine': 'Medicine',
    'Engineering': 'Engineering',
    'Environmental science': 'Environmental science',
    'Materials science': 'Materials science',
    'Mathematical analysis': 'Mathematics',
    'Geometry': 'Mathematics',
    'Philosophy': 'Philosophy',
    'Organic chemistry': 'Chemistry',
    'Economics': 'Economics',
    'Business': 'Economics',
    'Electrical engineering': 'Engineering',
    'Electronic engineering': 'Engineering',
    'Psychology': 'Psychology',
    'Political science': 'Political science',
    'Law': 'Law',
    'Geography': 'Geography',
    'Internal medicine': 'Medicine',
    'Geology': 'Geology',
    'Pure mathematics': 'Mathematics',
    'Biochemistry': 'Chemistry',
    'Sociology': 'Social sciences',
    'Thermodynamics': 'Physics',
    'Crystallography': 'Physics',
    'Control (management)': 'Management',
    'Epistemology': 'Philosophy',
    'Composite material': 'Materials science',
    'Mechanical engineering': 'Engineering',
    'Ecology': 'Environmental science',
    'Gene': 'Biology',
    'Pathology': 'Medicine',
    'Voltage': 'Physics',
    'Paleontology': 'Paleontology',
    'Genetics': 'Biology',
    'Archaeology': 'Archaeology',
    'Molecule': 'Chemistry',
    'Astronomy': 'Astronomy',
    'Applied mathematics': 'Mathematics',
    'Nuclear physics': 'Physics',
    'Image (mathematics)': 'Mathematics',
    'Optoelectronics': 'Engineering',
    'Acoustics': 'Physics',
    'Statistical physics': 'Physics',
    'Combinatorics': 'Mathematics',
    'Finance': 'Economics',
    'Control theory (sociology)': 'Social sciences',
    'Power (physics)': 'Physics',
    'Crystal structure': 'Physics',
    'Diffraction': 'Physics',
    'Context (archaeology)': 'Archaeology',
    'Art': 'Art',
    'Group (periodic table)': 'Chemistry',
    'Neuroscience': 'Medicine',
    'Condensed matter physics': 'Physics',
    'Atomic physics': 'Physics',
    'Disease': 'Medicine',
    'Mathematical optimization': 'Mathematics',
    "Endocrinology" : "Medicine",
    "Enzyme": "Biology",
    "Chromatography": "Chemistry",
    "Immunology": "Medicine",
    "Surgery": "Medicine",
    "Phisical chemistry": "Chemistry",
    "Physical chemistry": "Chemistry",
    "Anatomy": "Medicine",
    "Electron": "Physics",
    "Stereochemistry": "Chemistry",
    "Receptor": "Medicine",
    "Inorganic chemistry": "Chemistry",
    "Catalysis": "Chemistry",
    "Ion" : "Chemistry",
    "Queueing theory" : "Algorithms",
    "Queueing system" : "Algorithms",
    "Point (geometry)" : "Mathematics",
    "Service (business)" : "Economics",
    "Exponential function" : "Mathematics",
    "Element (criminal law)" : "Law",
    "Connection (principal bundle)" : "Mathematics",
    "Cognitive science" : "Psychology",
    "Tying" : "Economics",
    "Base (topology)"   : "Mathematics",
    "Operations research" : "Mathematics",
    "Mathematical economics"    : "Economics",
    "Point process" : "Mathematics",
    "Statistics" : "Mathematics",
    "Index (typography)" : "Linguistics",
    "Operations management" : "Economics",
    "Closing (real estate)" : "Economics",
    "Representation (politics)" : "Political science",
    "Analogy" : "Philosophy",
    "Marketing" : "Economics",
    "Listing (finance)" : "Economics",   
    "Line (geometry)" : "Mathematics",
    "Analog signal" : "Engineering",
    "Syntax" : "Linguistics",
    "Field (mathematics)" : "Mathematics",
    "Translation (biology)" : "Biology",
    "Transformation (genetics)" : "Biology",
    "Block (permutation group theory)" : "Mathematics",
    "Reliability (semiconductor)"  : "Engineering",
    "Evolutionary biology" : "Biology",
    "Function (biology)" : "Biology",
    "Probabilistic logic" : "Mathematics",
    "Embedded system" : "Engineering",
    "Plane (geometry)" : "Mathematics",
    "Mechanism (biology)" : "Biology",
    "Linear programming" : "Mathematics",
    "Reduction (mathematics)" : "Mathematics",
    "Nonlinear systems" : "Mathematics",
    "Reliability engineering" : "Engineering",
    "Detector" : "Physics",
    "Synchronization (alternating current)" : "Engineering",
    "Identification (biology)" : "Biology",
    "Motion (physics)" : "Physics",
    "Flexibility (engineering)" : "Engineering",
    "Nonlinear systems" : "Mathematics",
    "Phosphor" : "Chemistry",
    "Aerospace engineering" : "Engineering",
    "Electronic circuit" : "Engineering",
    "Induction motor" : "Engineering",
    "Inverter" : "Engineering",
    "Simple (philosophy)" : "Philosophy",
    "Matrix (chemical analysis)" : "Chemistry",
    "Control system" : "Engineering",
    "Realization (probability)" : "Mathematics",
    "Class (philosophy)" : "Philosophy",
    "Arithmetic" : "Mathematics",
    "Random variable" : "Mathematics",
    "Random variate" : "Mathematics",
    "Sequence (biology)" : "Biology",
    "Digital signal processing" : "Engineering",
    "Messenger RNA" : "Biology",
    "Filter (signal processing)" : "Engineering",
    "System engineering" : "Engineering",
    "Stress (linguistics)" : "Linguistics",
    "Combinational logic" : "Mathematics",
    "Markov chain" : "Mathematics",
    "Nonlinear systems" : "Mathematics",
    "Engineering drawing" : "Engineering",
    "Range (aeronautics)" : "Engineering",
    "Systems engineering" : "Engineering",
    "Chain (unit)" : "Chemistry",
    "Plotter": "Linguistics",
    "Countour line": "Linguistics",
    "Statistical analysis": "Mathematics",
    "Nonlinear system": "Mathematics",
    "Selection (genetic algorithm)": "Biology",
    "Pseudorandom binary sequence": "Mathematics",
    "Periodic sequence": "Mathematics",
    "Content (measure theory)": "Mathematics",
    "Sequential logic": "Mathematics",
    "Asynchronous circuit": "Engineering",
    "Control flow": "Engineering",
    "Robotics": "Engineering",
    "Robot" : "Engineering",
    "Work (physics)" : "Physics",
    "Topology (electrical circuits)" : "Engineering",
    "Synchronous circuit" : "Engineering",
    "Publishing" : "Literature",
    "Waveform" : "Engineering",
    "Graph" : "Mathematics",
    "Simulation" : "Engineering",
    "Quadratic programming" : "Mathematics",
    "Clock signal" : "Engineering",
    "Synchronizer" : "Engineering",
    "Contour line" : "Geography",
    "Cartography" : "Geography",
    "Circuit extraction" : "Engineering",
    "Circuit reliability" : "Engineering",
    "Radar" : "Engineering",
    "Intersymbol interference" : "Engineering",
    "Equivalent circuit" : "Engineering",
    "Heuristic" : "Mathematics",
    "Domain (mathematical analysis)" : "Mathematics",
    "Glycogen phosphorylase" : "Biology",
    "Ascorbic acid" : "Medicine", 
    "Politics" : "Political science",
    "CMOS" : "Engineering",
    "Algebra over a field" : "Mathematics",
    "Mass spectrum" : "Chemistry",
    "Mass spectrometry" : "Chemistry",
    "Nanotechnology": "Engineering",
}

colors = [
    "#1f77b4",  # blue
    "#ff7f0e",  # orange
    "#2ca02c",  # green
    "#d62728",  # red
    "#9467bd",  # purple
    "#8c564b",  # brown
    "#e377c2",  # pink
    "#7f7f7f",  # gray
    "#bcbd22",  # olive
    "#17becf",  # cyan

    "#393b79",  # dark blue
    "#637939",  # dark olive
    "#8c6d31",  # mustard
    "#843c39",  # dark red
    "#7b4173",  # plum
    "#3182bd",  # steel blue
    "#31a354",  # medium green
    "#756bb1",  # lavender
    "#636363",  # dark gray
    "#e6550d",  # burnt orange

    "#969696",  # light gray
    "#9c9ede",  # light purple
    "#cedb9c",  # pale green
    "#e7ba52",  # yellow
    "#e7969c",  # light red
    "#6baed6",  # light blue
    "#74c476",  # light green
    "#fd8d3c",  # light orange
    "#c49c94",  # tan
    "#bdbdbd",  # silver
]